const phones = [
    {
        id: 0,
        name: 'OnePlus 6 Pro',
        price: 24000,
        image: '6pro',
        cpu: 'Snapdragon 845',
        os: 'Android 8.1',
        sim: '2',
        ram: 8,
        rom: 256,
        camera: 16,
        display: 6.28,
        battery: 3700,
        description: 'OnePlus 6 Pro is a flagship smartphone from OnePlus. It was launched in May 2018. The phone comes with a 6.28-inch touchscreen display with a resolution of 1440 pixels by 3120 pixels at a PPI of 538 pixels per inch. OnePlus 6 Pro price in India starts from Rs. 39,999.'
    },
    {
        id: 1,
        name: 'OnePlus 7T Pro',
        price: 48000,
        image: '7tpro',
        cpu: 'Snapdragon 855+',
        os: 'Android 10',
        sim: '2',
        ram: 8,
        rom: 256,
        camera: 48,
        display: 6.67,
        battery: 4085,
        description: 'OnePlus 7T Pro is a flagship smartphone from OnePlus. It was launched in October 2019. The phone comes with a 6.67-inch touchscreen display with a resolution of 1440 pixels by 3120 pixels at a PPI of 516 pixels per inch. OnePlus 7T Pro price in India starts from Rs. 53,999.'
    },
    {
        id: 2,
        name: 'OnePlus 8',
        price: 0,
        image: '8',
        cpu: 'Snapdragon 865',
        os: 'Android 10',
        sim: '2',
        ram: 8,
        rom: 128,
        camera: 48,
        display: 6.55,
        battery: 4300,
        description: 'OnePlus 8 is a flagship smartphone from OnePlus. It was launched in April 2020. The phone comes with a 6.55-inch touchscreen display with a resolution of 1080 pixels by 2400 pixels at a PPI of 402 pixels per inch. OnePlus 8 price in India starts from Rs. 41,999.'
    },
    {
        id: 3,
        name: 'OnePlus 9R',
        price: 31000,
        image: '9r',
        cpu: 'Snapdragon 870',
        os: 'Android 11',
        sim: '2',
        ram: 8,
        rom: 128,
        camera: 48,
        display: 6.55,
        battery: 4500,
        description: 'OnePlus 9R is a flagship smartphone from OnePlus. It was launched in March 2021. The phone comes with a 6.55-inch touchscreen display with a resolution of 1080 pixels by 2400 pixels at a PPI of 402 pixels per inch. OnePlus 9R price in India starts from Rs. 39,999.'
    },
    {
        id: 4,
        name: 'OnePlus 5',
        price: 10000,
        image: '5',
        cpu: 'Snapdragon 835',
        os: 'Android 7.1',
        sim: '2',
        ram: 6,
        rom: 64,
        camera: 16,
        display: 5.5,
        battery: 3300,
        description: 'OnePlus 5 is a flagship smartphone from OnePlus. It was launched in June 2017. The phone comes with a 5.50-inch touchscreen display with a resolution of 1080 pixels by 1920 pixels at a PPI of 401 pixels per inch. OnePlus 5 price in India starts from Rs. 32,999.'
    }
];